# Generated by Django 5.0.6 on 2024-06-05 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travlr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='travlr.trip'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='travlr.trip'),
        ),
        migrations.AddField(
            model_name='daycost',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='travlr.trip'),
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='travlr.trip'),
        ),
    ]
