# Generated by Django 5.0.6 on 2024-06-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travlr', '0002_accomodation_trip_activity_trip_daycost_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayitinerary',
            name='accomodation_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='food_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='travel_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
