# Generated by Django 5.0.6 on 2024-06-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travlr', '0003_dayitinerary_accomodation_costs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomodation',
            new_name='Accommodation',
        ),
    ]
