# Generated by Django 5.0.6 on 2024-06-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travlr', '0004_rename_accomodation_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
