# Generated by Django 5.0.6 on 2024-06-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travlr', '0006_alter_activity_time_alter_daycost_cost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayitinerary',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
